#include "FancyWrite.h"
#include "FancyWrite_HeaderExample.t4generated.h"
#include <iostream>

void FancyWrite::WriteHello()
{
	std::cout << "Hello Bitches";
	std::cout << "ChangeToForceBuild";
	std::cout << TestAttribute; // print out the value generated by the text generation
	//new lines

}